site_name: Inkonfig Docs
site_url: https://docs.inkonfig.tk
repo_url: https://github.com/hexandcube/inkonfig
repo_name: GitHub
site_description: Documentation for Inkonfig - A Windows configuration script generator
site_author: Hexandcube
copyright: Copyright © 2021 Hexandcube 
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search
extra_css:
  - stylesheets/extra.css
theme:
  font:
    code: Space Mono
  name: material
  logo: assets/logo.png
  features:
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
  palette:
    primary: blue